### ISSUE TITLE
Clarification question regarding the MoTIF

### ISSUE THREAD

**Issue by xiang-deng** [aburns4/MoTIF#4]
Hi, congratulations on the amazing work, and thanks for sharing the resources! I just have some clarification questions and it would be very helpful if you could help provide some details.
1. There are 6125 traces in the `motif_all_raw_data` file, but it is further classified as _action_, _other_, _language_ and _exploration_. Could you elaborate more on the differences between them?
2. Is there an official test split for MoTIF or does the released data only include the training split, and the test set is held out? The comprehensive experiment settings in the paper are very helpful, but could you elaborate more on the actual ratio/#examples that are used for train/dev/test?
3. In the paper, you mentioned that each task is annotated by 5 workers. There is some discussion regarding the agreement on task feasibility in the paper. But as mentioned in the paper, multiple workers may result in different trajectories for accomplishing the same task. Is there some statistics on this? In particular, how are these tasks handled for the testing examples? Does the testing set only include one example of each (app, task) pair, and is the operation considered successful as long as the predicted sequence matches one of the ground truth demonstrations?
4. Also, it is mentioned in the appendix that you build an offline evaluation environment for each app by combining all observations in training. Is it possible for the model to predict actions that are not seen, and what will be the transition in that case, or will it be considered a fail immediately?

**Comment by aburns4** [comment]
Hi there, thank you! Let me address your questions.

1. Thanks for pointing this out- I created a more generic version of the data for public use and had not yet had the chance to update my repo README, I will do that shortly. Here is some context:
    - Action: Traces that were collected for task automation. They contain task information, screen captures, view hierarchies, and other metadata.
    - Language: Traces that were collected as a _byproduct_ of collecting the original language annotations. At the time we only retained the screen captures for these since the view hierarchies take up a lot of space. The folders contain all of the commands our human annotators wrote for that app as comma separated. Unfortunately comma separated wasn't the best idea so they could use some cleaning to get the correct atomic commands from the string. 
    - Exploration: Additional traces we collected where we instructed users to try to explore as much of an app as possible. This was only done for a subset of apps and ultimately was not used for the offline env since it made it a bit noisier, but we release it since it has additional screens and view hierarchies and may be useful to folks.
    - Other: Traces that could have been any of the above but were missing metadata or may have had some technical glitch. But we include them in case they can serve as extra noisy data or be used in new ways for other uses.

3. Yes, the train/test split for task feasibility classification is already provided in the linked [`data.tar.gz`](https://drive.google.com/file/d/1GSVA8sz-SKcioNhCq1lWH58x_u5FXfDQ/view) under the task feasibility [folder](https://github.com/aburns4/MoTIF/tree/main/task_feasibility). The train/test splits for task automation are already provided [here](https://github.com/aburns4/MoTIF/tree/main/task_automation/seq2act/motif_data_generation), e.g. `eccv_motif_app_unseen_task_unseen.json`.  App seen task unseen (all) and app unseen task unseen are reflected in Table 4 of the [paper](https://arxiv.org/pdf/2202.02312.pdf), app unseen task seen and app seen task unseen (curr) are reflected in Table 14 of the supplementary. The test set is approximately 10% of the full data, there is no dev set due to the size of the dataset.

4. Good point. We allow all types of trajectories for a given task in our training and evaluation. I do not have statistics for how often the trajectories vary. But at test time, all 5 trajectories are evaluated, so you can think of them as just being averaged over, which might not result in the highest metrics. Instead, you could change the metric to allow for only one of the five trajectories to be satisfied to count as successful. I'll leave it to you or future work if you care to change the metric, what you're suggesting is reasonable.

5. Yes, you're correct- it is possible for the model to predict actions that are not seen. We retain the same behavior to environment failures as Seq2Seq and MOCA with minor modification: as in the original work, there is a max number of failures allowed before the evaluation is terminated. I believe it was set to 20 and we kept that value the same.

    I think for MOCA, when interacting with the offline env, we built a graph that narrowed the grounding scope to only elements seen with the predicted action class. As in, if the model at time step t predicts the action to take is click, we only allow for localization on the options for which "click" has been seen. This is of course imperfect since we haven't necessarily seen all clickable elements be clicked on, but it ultimately makes it easier to localize correctly since it reduces the number of possible elements. Then, the closest bounding box amongst the remaining elements (closest to the predicted bounding point or point) is the element interacted with for that time step.

    If the action class result in an empty list of elements, i.e., no elements were seen with that action class (e.g. type or swipe, which are less common), if I remember correctly we consider this a failure, which counts towards the max 20 allowed before the evaluation of this trace is completed.

    I have been meaning to eventually add the VLN code here, it just wasn't a priority since it wasn't the highest performing. I could be misremembering the details above regarding the offline env so releasing the code will jog my memory and allow you to reproduce the same set up. I will do that in the coming weeks after a deadline passes so hopefully it can be of use to you then. Thank you for your patience!

**Comment by xiang-deng** [comment]
Thanks a lot for the detailed answer. This is very helpful!

**Comment by aburns4** [comment]
By the way, I have updated the primary README on the repo if it's of any use!
